### PR TITLE
Example for Java.

### PR DESCRIPTION
**Pull request by IlyaKornakov**

### CODE REVIEW

**Comment by mvlevin** [comment]
I suggest to rewrite this into canonical form in terms of reading/writing data fast, as we agreed before.

Also, was_founded should be renamed to was_found or just found, because founded means a different thing :)

**Comment by astiunov** [comment]
I can add Fast Scanner class to Java solution from http://neerc.ifmo.ru/trains/information/Template.java. It seems to me, that std::ios_base::sync_with_stdio(false) is enough for C++.

Ok, I'll rename it in the next version with classes.

**Comment by mvlevin** [comment]
std::ios_base::sync_with_stdio(false) is enough for C++ as soon as 1) first go all cin >>, then go all cout << 2) you always use "\n" instead of std::endl. Why? Because every time you use std::endl and every time you interchange cin and cout, the buffer is flushed, and that starts to work at least 3 times slower than scanf/printf. Those are unfortunate complexities, but they exist. We can hope that students won't change are read/write code themselves and we'll be ok. However, in the case of queries, if they are first read, then outputs are written, this can be slow. I suggest at least checking how much slower it is, so that we don't have to make time limit too high because of that. If that's not significant, it's better to stay with cin/cout instead of scanf/printf, of course.

**Comment by astiunov** [comment]
Yeah, I know about buffering. In my opinion, it's not so many queries (about $10^5$) in the majority of problems, so we can just use sync... regardless of buffering and etс.

**Comment by mvlevin** [comment]
I'm completely sure that for $10^6$ queries it becomes a considerable overhead. I'm not sure about $10^5$, but that's exactly the order of magnitude starting from which I recommend my students either using printf/scanf or be very careful with cin/cout. $10^4$ is definitely no problem. So, I'd suggest to test the $10^5$ case and compare the timings of read/write with the timings of the solution itself.

**Comment by astiunov** [comment]
I've already tested cin/cout without sync for 10^5 queries (first read all, then output all), and it's fast enough --- it takes about 400 ms for the entire solution.

**Comment by astiunov** [comment]
So I've tested 4 solution's variants:
- read all, then write all, with sync (577 ms)
- read all, then write all, without sync (311 ms)
- read one, write one, with sync (670 ms)
- read one, write one, without sync (420) ms

So I think the last one is the optimal variant

**Comment by mvlevin** [comment]
If by "with sync" you mean std::ios_base::sync_with_stdio(false), then it makes sense :) Although I would call this "without sync" :)

**Comment by astiunov** [comment]
You're right, fixed it :)

**Pull request merged**
